#pragma once

#define BPX_SDK_PROJECT_NAME "bpx_sdk"
#define BPX_SDK_PROJECT_VERSION "1.0.6"
#define BPX_SDK_VERSION_MAJOR 1
#define BPX_SDK_VERSION_MINOR 0
#define BPX_SDK_VERSION_PATCH 6
#define BPX_SDK_GIT_COMMIT_HASH "8779ca0"
